name: Update Website

on:
  push:
    branches:
      - main

jobs:
  update_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          git clone https://github.com/hectormra23/BIology_Club_Page_Web.git C:\Users\hecto\OneDrive\Escritorio\BIology_Club_Page_Web-main
          cp -R ${{ github.workspace }}/* /path/to/your/local/directory
          cd /path/to/your/local/directory
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update website from GitHub Desktop"
          git push

